import type { ChartDefinition } from "./types";

const colors = {
  amber: "#fbbf24",
  blue: "#60a5fa",
  cyan: "#22d3ee",
  emerald: "#34d399",
  fuchsia: "#e879f9",
  indigo: "#818cf8",
  lime: "#a3e635",
  orange: "#fb923c",
  pink: "#f472b6",
  red: "#f87171",
  slate: "#94a3b8",
  violet: "#a78bfa",
} as const;

export const chartDefinitions: ChartDefinition[] = [
  {
    id: "supply-demand",
    group: "Grid conditions",
    title: "Supply and demand",
    description: "Actual demand, forecast demand, and available ERCOT generation capacity.",
    unit: "MW",
    sourceId: "supply_demand",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/supplyanddemand",
    series: [
      {
        id: "demand",
        label: "Actual demand",
        metric: "ercot.supply_demand.demand_mw",
        color: colors.emerald,
      },
      {
        id: "forecast-demand",
        label: "Forecast demand",
        metric: "ercot.supply_demand.forecast_demand_mw",
        color: colors.cyan,
      },
      {
        id: "available-capacity",
        label: "Available capacity",
        metric: "ercot.supply_demand.available_capacity_mw",
        color: colors.amber,
      },
    ],
  },
  {
    id: "frequency",
    group: "Grid conditions",
    title: "Grid frequency",
    description: "System frequency around the nominal 60 Hz operating point.",
    unit: "Hz",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "frequency",
        label: "Frequency",
        metric: "ercot.Frequency.Current_Frequency",
        color: colors.emerald,
      },
    ],
  },
  {
    id: "reserves",
    group: "Grid conditions",
    title: "Operating reserves",
    description: "Physical responsive capability and ancillary capacity published by ERCOT.",
    unit: "MW",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/ancillaryservices",
    spikeCritical: true,
    series: [
      {
        id: "prc",
        label: "Physical responsive capability",
        metric: "ercot_ancillary.prc",
        color: colors.blue,
      },
      {
        id: "reg-up",
        label: "Regulation up",
        metric: "ercot_ancillary.regUpAwd",
        color: colors.violet,
      },
      {
        id: "reg-down",
        label: "Regulation down",
        metric: "ercot_ancillary.regDownAwd",
        color: colors.fuchsia,
      },
    ],
  },
  {
    id: "fuel-mix",
    group: "Generation",
    title: "Fuel mix generation",
    description: "Five-minute generation by major ERCOT fuel category without smoothing.",
    unit: "MW",
    sourceId: "fuel_mix",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/fuelmix",
    series: [
      {
        id: "natural-gas",
        label: "Natural gas",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:natural_gas"],
        color: colors.amber,
      },
      {
        id: "wind",
        label: "Wind",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:wind"],
        color: colors.cyan,
      },
      {
        id: "solar",
        label: "Solar",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:solar"],
        color: colors.orange,
      },
      {
        id: "coal",
        label: "Coal and lignite",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:coal_and_lignite"],
        color: colors.slate,
      },
      {
        id: "nuclear",
        label: "Nuclear",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:nuclear"],
        color: colors.indigo,
      },
      {
        id: "power-storage",
        label: "Power storage",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:power_storage"],
        color: colors.pink,
      },
    ],
  },
  {
    id: "storage",
    group: "Generation",
    title: "Energy storage resources",
    description: "Charging is published as negative load; discharging is positive generation.",
    unit: "MW",
    sourceId: "energy_storage",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/energystorageresources",
    spikeCritical: true,
    series: [
      {
        id: "charging",
        label: "Charging",
        metric: "ercot.storage.charging_mw",
        color: colors.pink,
      },
      {
        id: "discharging",
        label: "Discharging",
        metric: "ercot.storage.discharging_mw",
        color: colors.emerald,
      },
      {
        id: "net-output",
        label: "Net output",
        metric: "ercot.storage.net_output_mw",
        color: colors.blue,
      },
    ],
  },
  {
    id: "renewables",
    group: "Generation",
    title: "Wind and solar outlook",
    description: "Hourly actual, short-term forecast, and current operating-plan HSL.",
    unit: "MW",
    sourceId: "wind_solar",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/combinedwindandsolar",
    series: [
      {
        id: "wind-actual",
        label: "Wind actual",
        metric: "ercot.renewables.actual_mw",
        tags: ["resource:wind"],
        color: colors.cyan,
      },
      {
        id: "wind-forecast",
        label: "Wind forecast",
        metric: "ercot.renewables.forecast_mw",
        tags: ["resource:wind"],
        color: colors.blue,
      },
      {
        id: "wind-hsl",
        label: "Wind HSL",
        metric: "ercot.renewables.hsl_mw",
        tags: ["resource:wind"],
        color: colors.indigo,
      },
      {
        id: "solar-actual",
        label: "Solar actual",
        metric: "ercot.renewables.actual_mw",
        tags: ["resource:solar"],
        color: colors.amber,
      },
      {
        id: "solar-forecast",
        label: "Solar forecast",
        metric: "ercot.renewables.forecast_mw",
        tags: ["resource:solar"],
        color: colors.orange,
      },
    ],
  },
  {
    id: "generation-outages",
    group: "Reliability",
    title: "Generation outages",
    description: "Planned and unplanned dispatchable and renewable generation outages.",
    unit: "MW",
    sourceId: "generation_outages",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/generationoutages",
    spikeCritical: true,
    series: [
      {
        id: "dispatchable-unplanned",
        label: "Dispatchable unplanned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:dispatchable", "outage_type:unplanned"],
        color: colors.red,
      },
      {
        id: "dispatchable-planned",
        label: "Dispatchable planned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:dispatchable", "outage_type:planned"],
        color: colors.orange,
      },
      {
        id: "renewable-unplanned",
        label: "Renewable unplanned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:renewable", "outage_type:unplanned"],
        color: colors.fuchsia,
      },
      {
        id: "renewable-planned",
        label: "Renewable planned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:renewable", "outage_type:planned"],
        color: colors.violet,
      },
    ],
  },
  {
    id: "pricing",
    group: "Market",
    title: "Settlement point prices",
    description: "Selected ERCOT real-time settlement point prices; negative prices are preserved.",
    unit: "$/MWh",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_spp",
    spikeCritical: true,
    series: [
      {
        id: "houston",
        label: "Houston hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_HOUSTON"],
        color: colors.emerald,
      },
      {
        id: "north",
        label: "North hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_NORTH"],
        color: colors.blue,
      },
      {
        id: "west",
        label: "West hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_WEST"],
        color: colors.orange,
      },
    ],
  },
  {
    id: "dc-ties",
    group: "Market",
    title: "DC tie flows",
    description:
      "Individual ERCOT DC tie flows; the source sign convention is shown without inversion.",
    unit: "MW",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "east",
        label: "DC East",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_E"],
        color: colors.cyan,
      },
      {
        id: "north",
        label: "DC North",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_N"],
        color: colors.amber,
      },
      {
        id: "south",
        label: "DC South",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_S"],
        color: colors.fuchsia,
      },
    ],
  },
];

export const chartGroups = [...new Set(chartDefinitions.map((definition) => definition.group))];

export function seriesKey(chartId: string, seriesId: string) {
  return `${chartId}:${seriesId}`;
}
