import type { ChartDefinition } from "./types";

const colors = {
  amber: "#fbbf24",
  blue: "#60a5fa",
  cyan: "#22d3ee",
  emerald: "#34d399",
  fuchsia: "#e879f9",
  indigo: "#818cf8",
  lime: "#a3e635",
  orange: "#fb923c",
  pink: "#f472b6",
  red: "#f87171",
  slate: "#94a3b8",
  violet: "#a78bfa",
} as const;

export const chartDefinitions: ChartDefinition[] = [
  {
    id: "supply-demand",
    group: "Grid conditions",
    title: "Supply and demand",
    description: "Actual demand, forecast demand, and available ERCOT generation capacity.",
    unit: "MW",
    sourceId: "supply_demand",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/supplyanddemand",
    series: [
      {
        id: "demand",
        label: "Actual demand",
        metric: "ercot.supply_demand.demand_mw",
        color: colors.emerald,
      },
      {
        id: "forecast-demand",
        label: "Forecast demand",
        metric: "ercot.supply_demand.forecast_demand_mw",
        color: colors.cyan,
      },
      {
        id: "available-capacity",
        label: "Available capacity",
        metric: "ercot.supply_demand.available_capacity_mw",
        color: colors.amber,
      },
    ],
  },
  {
    id: "frequency",
    group: "Grid conditions",
    title: "Grid frequency",
    description: "System frequency around the nominal 60 Hz operating point.",
    unit: "Hz",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "frequency",
        label: "Frequency",
        metric: "ercot.Frequency.Current_Frequency",
        color: colors.emerald,
      },
    ],
  },
  {
    id: "reserves",
    group: "Grid conditions",
    title: "Operating reserves",
    description: "Physical responsive capability and ancillary capacity published by ERCOT.",
    unit: "MW",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/ancillaryservices",
    spikeCritical: true,
    series: [
      {
        id: "prc",
        label: "Physical responsive capability",
        metric: "ercot_ancillary.prc",
        color: colors.blue,
      },
      {
        id: "reg-up",
        label: "Regulation up",
        metric: "ercot_ancillary.regUpAwd",
        color: colors.violet,
      },
      {
        id: "reg-down",
        label: "Regulation down",
        metric: "ercot_ancillary.regDownAwd",
        color: colors.fuchsia,
      },
    ],
  },
  {
    id: "fuel-mix",
    group: "Generation",
    title: "Fuel mix generation",
    description: "Five-minute generation by major ERCOT fuel category without smoothing.",
    unit: "MW",
    sourceId: "fuel_mix",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/fuelmix",
    series: [
      {
        id: "natural-gas",
        label: "Natural gas",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:natural_gas"],
        color: colors.amber,
      },
      {
        id: "wind",
        label: "Wind",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:wind"],
        color: colors.cyan,
      },
      {
        id: "solar",
        label: "Solar",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:solar"],
        color: colors.orange,
      },
      {
        id: "coal",
        label: "Coal and lignite",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:coal_and_lignite"],
        color: colors.slate,
      },
      {
        id: "nuclear",
        label: "Nuclear",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:nuclear"],
        color: colors.indigo,
      },
      {
        id: "power-storage",
        label: "Power storage",
        metric: "ercot.fuel_mix.generation_mw",
        tags: ["fuel:power_storage"],
        color: colors.pink,
      },
    ],
  },
  {
    id: "storage",
    group: "Generation",
    title: "Energy storage resources",
    description: "Charging is published as negative load; discharging is positive generation.",
    unit: "MW",
    sourceId: "energy_storage",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/energystorageresources",
    spikeCritical: true,
    series: [
      {
        id: "charging",
        label: "Charging",
        metric: "ercot.storage.charging_mw",
        color: colors.pink,
      },
      {
        id: "discharging",
        label: "Discharging",
        metric: "ercot.storage.discharging_mw",
        color: colors.emerald,
      },
      {
        id: "net-output",
        label: "Net output",
        metric: "ercot.storage.net_output_mw",
        color: colors.blue,
      },
    ],
  },
  {
    id: "renewables",
    group: "Generation",
    title: "Wind and solar outlook",
    description: "Hourly actual, short-term forecast, and current operating-plan HSL.",
    unit: "MW",
    sourceId: "wind_solar",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/combinedwindandsolar",
    series: [
      {
        id: "wind-actual",
        label: "Wind actual",
        metric: "ercot.renewables.actual_mw",
        tags: ["resource:wind"],
        color: colors.cyan,
      },
      {
        id: "wind-forecast",
        label: "Wind forecast",
        metric: "ercot.renewables.forecast_mw",
        tags: ["resource:wind"],
        color: colors.blue,
      },
      {
        id: "wind-hsl",
        label: "Wind HSL",
        metric: "ercot.renewables.hsl_mw",
        tags: ["resource:wind"],
        color: colors.indigo,
      },
      {
        id: "solar-actual",
        label: "Solar actual",
        metric: "ercot.renewables.actual_mw",
        tags: ["resource:solar"],
        color: colors.amber,
      },
      {
        id: "solar-forecast",
        label: "Solar forecast",
        metric: "ercot.renewables.forecast_mw",
        tags: ["resource:solar"],
        color: colors.orange,
      },
    ],
  },
  {
    id: "generation-outages",
    group: "Reliability",
    title: "Generation outages",
    description: "Planned and unplanned dispatchable and renewable generation outages.",
    unit: "MW",
    sourceId: "generation_outages",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/generationoutages",
    spikeCritical: true,
    series: [
      {
        id: "dispatchable-unplanned",
        label: "Dispatchable unplanned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:dispatchable", "outage_type:unplanned"],
        color: colors.red,
      },
      {
        id: "dispatchable-planned",
        label: "Dispatchable planned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:dispatchable", "outage_type:planned"],
        color: colors.orange,
      },
      {
        id: "renewable-unplanned",
        label: "Renewable unplanned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:renewable", "outage_type:unplanned"],
        color: colors.fuchsia,
      },
      {
        id: "renewable-planned",
        label: "Renewable planned",
        metric: "ercot.generation_outages.mw",
        tags: ["category:renewable", "outage_type:planned"],
        color: colors.violet,
      },
    ],
  },
  {
    id: "pricing",
    group: "Market",
    title: "Settlement point prices",
    description: "Selected ERCOT real-time settlement point prices; negative prices are preserved.",
    unit: "$/MWh",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_spp",
    spikeCritical: true,
    series: [
      {
        id: "houston",
        label: "Houston hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_HOUSTON"],
        color: colors.emerald,
      },
      {
        id: "north",
        label: "North hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_NORTH"],
        color: colors.blue,
      },
      {
        id: "west",
        label: "West hub",
        metric: "ercot.pricing",
        tags: ["ercot_region:HB_WEST"],
        color: colors.orange,
      },
    ],
  },
  {
    id: "dc-ties",
    group: "Market",
    title: "DC tie flows",
    description:
      "Individual ERCOT DC tie flows; the source sign convention is shown without inversion.",
    unit: "MW",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "east",
        label: "DC East",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_E"],
        color: colors.cyan,
      },
      {
        id: "north",
        label: "DC North",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_N"],
        color: colors.amber,
      },
      {
        id: "south",
        label: "DC South",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_S"],
        color: colors.fuchsia,
      },
      {
        id: "laredo",
        label: "DC Laredo",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_L"],
        color: colors.lime,
      },
      {
        id: "railroad",
        label: "DC Railroad",
        metric: "ercot.DC_Tie_Flows",
        tags: ["ercot_dc_tie:DC_R"],
        color: colors.pink,
      },
      {
        id: "net",
        label: "Net interchange",
        derive: {
          operation: "sum",
          from: ["east", "north", "south", "laredo", "railroad"],
        },
        color: colors.emerald,
      },
      {
        id: "total",
        label: "Total absolute flow",
        derive: {
          operation: "sum_abs",
          from: ["east", "north", "south", "laredo", "railroad"],
        },
        color: colors.slate,
      },
    ],
  },
  {
    id: "capacity-headroom",
    group: "Grid conditions",
    title: "Unused capacity and headroom",
    description: "Available system capacity minus actual system demand, alongside PRC.",
    unit: "MW",
    sourceId: "ercot_realtime",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "capacity",
        label: "System capacity",
        metric: "ercot.Real_Time_Data.Total_System_Capacity",
        color: colors.blue,
      },
      {
        id: "demand",
        label: "System demand",
        metric: "ercot.Real_Time_Data.Actual_System_Demand",
        color: colors.emerald,
      },
      {
        id: "headroom",
        label: "Unused capacity",
        derive: { operation: "subtract", from: ["capacity", "demand"] },
        color: colors.amber,
      },
      {
        id: "prc",
        label: "Physical responsive capability",
        metric: "ercot_ancillary.prc",
        color: colors.violet,
      },
    ],
  },
  {
    id: "time-error",
    group: "Grid conditions",
    title: "Time error and delta",
    description: "ERCOT instantaneous time error and the change between consecutive readings.",
    unit: "seconds",
    sourceId: "ercot_realtime",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    spikeCritical: true,
    series: [
      {
        id: "time-error",
        label: "Instantaneous time error",
        metric: "ercot.Frequency.Instantaneous_Time_Error",
        color: colors.blue,
      },
      {
        id: "delta",
        label: "Time error delta",
        derive: { operation: "delta", from: ["time-error"] },
        color: colors.amber,
      },
    ],
  },
  {
    id: "inertia",
    group: "Grid conditions",
    title: "System inertia",
    description: "Current ERCOT system inertia from the real-time conditions feed.",
    unit: "GW·s",
    sourceId: "ercot_realtime",
    sourceUrl: "https://www.ercot.com/content/cdr/html/real_time_system_conditions.html",
    series: [
      {
        id: "inertia",
        label: "System inertia",
        metric: "ercot.Real_Time_Data.Current_System_Inertia",
        color: colors.indigo,
      },
    ],
  },
  {
    id: "eea",
    group: "Reliability",
    title: "Emergency Energy Alert level",
    description: "Discrete ERCOT EEA state collected from the daily PRC dashboard.",
    unit: "level",
    sourceId: "ercot_eea",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/dailyprc",
    series: [
      {
        id: "level",
        label: "EEA level",
        metric: "ercot.eea_level",
        color: colors.red,
      },
    ],
  },
  {
    id: "ancillary-regulation",
    group: "Ancillary services",
    title: "Regulation awards",
    description: "Regulation-up and regulation-down awards from the ancillary capacity monitor.",
    unit: "MW",
    sourceId: "ercot_ancillary",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/ancillaryservices",
    series: [
      {
        id: "reg-up",
        label: "Regulation up",
        metric: "ercot_ancillary.regUpAwd",
        color: colors.blue,
      },
      {
        id: "reg-down",
        label: "Regulation down",
        metric: "ercot_ancillary.regDownAwd",
        color: colors.fuchsia,
      },
    ],
  },
  {
    id: "ancillary-reserves",
    group: "Ancillary services",
    title: "Real-time reserve capacity",
    description: "Online and online/offline real-time reserve capacity.",
    unit: "MW",
    sourceId: "ercot_ancillary",
    sourceUrl: "https://www.ercot.com/gridmktinfo/dashboards/ancillaryservices",
    series: [
      {
        id: "online",
        label: "Online reserve",
        metric: "ercot_ancillary.rtReserveOnline",
        color: colors.emerald,
      },
      {
        id: "on-offline",
        label: "Online/offline reserve",
        metric: "ercot_ancillary.rtReserveOnOffline",
        color: colors.orange,
      },
      {
        id: "nonspin",
        label: "Non-spin off generation",
        metric: "ercot_ancillary.nsrCapOffGen",
        color: colors.violet,
      },
      {
        id: "ecrs",
        label: "ECRS quick start",
        metric: "ercot_ancillary.ecrsCapQs",
        color: colors.cyan,
      },
    ],
  },
  {
    id: "customer-outages",
    group: "Reliability",
    title: "PowerOutage.us customer outages",
    description: "Total reported Texas customers without power across county observations.",
    unit: "customers",
    sourceId: "poweroutages_us",
    sourceUrl: "https://poweroutage.us/area/state/texas",
    series: [
      {
        id: "customers",
        label: "Customers without power",
        metric: "poweroutageus.customers",
        rollup: "sum",
        color: colors.red,
      },
    ],
  },
  {
    id: "weather-temperature",
    group: "Weather",
    title: "Nearby METAR temperature",
    description: "Airport observations near major ERCOT load and generation centers.",
    unit: "°C",
    sourceId: "metar",
    sourceUrl: "https://aviationweather.gov/data/api/",
    series: [
      {
        id: "dfw",
        label: "Dallas/Fort Worth",
        metric: "metar.temperature",
        tags: ["metar_code:KDFW"],
        color: colors.blue,
      },
      {
        id: "austin",
        label: "Austin",
        metric: "metar.temperature",
        tags: ["metar_code:KAUS"],
        color: colors.emerald,
      },
      {
        id: "houston",
        label: "Houston",
        metric: "metar.temperature",
        tags: ["metar_code:KHOU"],
        color: colors.amber,
      },
      {
        id: "san-antonio",
        label: "San Antonio",
        metric: "metar.temperature",
        tags: ["metar_code:KSAT"],
        color: colors.fuchsia,
      },
    ],
  },
  {
    id: "weather-wind",
    group: "Weather",
    title: "Nearby METAR wind speed",
    description: "Observed airport wind speeds in miles per hour.",
    unit: "mph",
    sourceId: "metar",
    sourceUrl: "https://aviationweather.gov/data/api/",
    series: [
      {
        id: "dfw",
        label: "Dallas/Fort Worth",
        metric: "metar.winds.speed",
        tags: ["metar_code:KDFW"],
        color: colors.blue,
      },
      {
        id: "austin",
        label: "Austin",
        metric: "metar.winds.speed",
        tags: ["metar_code:KAUS"],
        color: colors.emerald,
      },
      {
        id: "houston",
        label: "Houston",
        metric: "metar.winds.speed",
        tags: ["metar_code:KHOU"],
        color: colors.amber,
      },
      {
        id: "san-antonio",
        label: "San Antonio",
        metric: "metar.winds.speed",
        tags: ["metar_code:KSAT"],
        color: colors.fuchsia,
      },
    ],
  },
  {
    id: "collector-duty-cycle",
    group: "Operations",
    title: "Collector duty cycle",
    description: "Internal collection-loop utilization by source.",
    unit: "%",
    sourceUrl: "https://github.com/venku122/ercot-dashboard",
    series: [
      {
        id: "grid",
        label: "Grid",
        metric: "ercot.app.duty_cycle",
        tags: ["app:ercot_realtime"],
        color: colors.blue,
      },
      {
        id: "ancillary",
        label: "Ancillary",
        metric: "ercot.app.duty_cycle",
        tags: ["app:ercot_ancillary"],
        color: colors.violet,
      },
      {
        id: "pricing",
        label: "Pricing",
        metric: "ercot.app.duty_cycle",
        tags: ["app:ercot_pricing"],
        color: colors.amber,
      },
      {
        id: "weather",
        label: "METAR",
        metric: "ercot.app.duty_cycle",
        tags: ["app:metar"],
        color: colors.emerald,
      },
      {
        id: "outages",
        label: "Outages",
        metric: "ercot.app.duty_cycle",
        tags: ["app:poweroutages_us"],
        color: colors.red,
      },
      {
        id: "eea",
        label: "EEA",
        metric: "ercot.app.duty_cycle",
        tags: ["app:ercot_eea"],
        color: colors.fuchsia,
      },
    ],
  },
];

export const chartGroups = [...new Set(chartDefinitions.map((definition) => definition.group))];

export function seriesKey(chartId: string, seriesId: string) {
  return `${chartId}:${seriesId}`;
}
